version: 0.2
phases:
  build:
    commands:
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name poc-sam-sample-app -t template.yaml --s3-bucket sam-cli-bucket-templates-us-west-2-dev --capabilities CAPABILITY_IAM
        