version: 0.2
env:
  secrets-manager:
    SECRET: db-connection-secret
phases:
  install:
    # runtime-versions:
    #   dotnet: 3.1
    commands:
      - apt-get update
      - apt-get install -y jq mysql-client
  pre_build:
    commands:
      - echo "Getting Database details.."
      - DBSERVER=$(echo $SECRET | jq -r '.host')
      - DBUser=$(echo $SECRET | jq -r '.username')
      - DBPassword=$(echo $SECRET | jq -r '.password')
      - echo "my username ${DBUser}"
  build:
    commands:
      - echo "List source folder.."
      - ls -la
  post_build:
    commands:
      - echo "Connecting to ${DBSERVER} & running MySQL query.."
      - mysql -h ${DBSERVER} -P 3306 -u ${DBUser} -p${DBPassword} poccicd < database.sql
      - echo "Done."