-- MySQL Script generated by MySQL Workbench
-- Wed Aug 25 18:43:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `mydb`.`subreports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subreports` (
  `idsubreports` BIGINT NOT NULL AUTO_INCREMENT,
  `scheme_identifier` NVARCHAR(36) NOT NULL,
  `params` JSON NOT NULL,
  `report_body_id` NVARCHAR(36) NOT NULL,
  PRIMARY KEY (`idsubreports`, `report_body_id`),
  INDEX `fk_subreports_report_bodies_idx` (`report_body_id` ASC) ,
  CONSTRAINT `fk_subreports_report_bodies`
    FOREIGN KEY (`report_body_id`)
    REFERENCES `report_palace`.`report_bodies` (`report_body_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
